### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds two buttons to get your app on F-Droid and Google Play 👍 

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

### CODE REVIEW

**Comment by bancek** [comment]
Thanks for your suggestion. Please also add [Download on App Store](https://apps.apple.com/app/koofr-vault/id6468869124) badge for iOS. The order of badges should be Google Play, App Store, F-Droid (the same as we have on Vault web page).

**Comment by Poussinou** [comment]
What should be the source for the image of the badge?

**Comment by bancek** [comment]
https://developer.apple.com/app-store/marketing/guidelines/images/badge-example-preferred.png

**Comment by Poussinou** [comment]
The Apple badge doesn't really fit with the two others.

**Comment by licaon-kter** [comment]
@bancek why are Issues disabled here? 

Wanted to ask you to rewrite the text in https://changelog.koofr.net/koofr-vault-has-been-added-to-f-droid-store!-296402

This part of the text is not true:
> During this process, the code was checked for potential security or privacy issues to ensure that it is safe to install. It is a revision of our work and a guarantee that Koofr Vault does what it promises

**Comment by bancek** [comment]
@licaon-kter support for Koofr Vault is only available through email support@koofr.net and Koofr subreddit. The content team will fix the changelog. Thanks for reporting this.

**Comment by licaon-kter** [comment]
@bancek Remove this line via a MR: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.koofr.vault.yml#L10 and add this info in:  https://github.com/koofr/vault/blob/main/fastlane/metadata/android/en-US/full_description.txt

**Comment by bancek** [comment]
@licaon-kter we've updated our changelog

**Pull request merged**
